//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementServiceUIWebService.ManagementServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JoBTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JoBTitle {
            get {
                return this.JoBTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JoBTitleField, value) != true)) {
                    this.JoBTitleField = value;
                    this.RaisePropertyChanged("JoBTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttendenceBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AttendenceBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AttendenceIDField;
        
        private int EmployeeIDField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AttendenceID {
            get {
                return this.AttendenceIDField;
            }
            set {
                if ((this.AttendenceIDField.Equals(value) != true)) {
                    this.AttendenceIDField = value;
                    this.RaisePropertyChanged("AttendenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerfomanceBO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PerfomanceBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PerfomanceIDField;
        
        private int EmployeeIDField;
        
        private System.DateTime ReviewDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PerfomanceID {
            get {
                return this.PerfomanceIDField;
            }
            set {
                if ((this.PerfomanceIDField.Equals(value) != true)) {
                    this.PerfomanceIDField = value;
                    this.RaisePropertyChanged("PerfomanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ReviewDate {
            get {
                return this.ReviewDateField;
            }
            set {
                if ((this.ReviewDateField.Equals(value) != true)) {
                    this.ReviewDateField = value;
                    this.RaisePropertyChanged("ReviewDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Goal {
            get {
                return this.GoalField;
            }
            set {
                if ((object.ReferenceEquals(this.GoalField, value) != true)) {
                    this.GoalField = value;
                    this.RaisePropertyChanged("Goal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagementServiceReference1.ManagementServiceSoap")]
    public interface ManagementServiceSoap {
        
        // CODEGEN: Generating message contract since element name employeeBO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertEmployee", ReplyAction="*")]
        ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse insertEmployee(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse> insertEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name employeeBO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateEmployee", ReplyAction="*")]
        ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse updateEmployee(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse> updateEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name employeeBO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEmployee", ReplyAction="*")]
        ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse deleteEmployee(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse> deleteEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name attendenceBO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAttendence", ReplyAction="*")]
        ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse AddAttendence(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAttendence", ReplyAction="*")]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse> AddAttendenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest request);
        
        // CODEGEN: Generating message contract since element name perfomanceBO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerformence", ReplyAction="*")]
        ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse AddPerformence(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerformence", ReplyAction="*")]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse> AddPerformenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequestBody Body;
        
        public insertEmployeeRequest() {
        }
        
        public insertEmployeeRequest(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO;
        
        public insertEmployeeRequestBody() {
        }
        
        public insertEmployeeRequestBody(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            this.employeeBO = employeeBO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponseBody Body;
        
        public insertEmployeeResponse() {
        }
        
        public insertEmployeeResponse(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertEmployeeResult;
        
        public insertEmployeeResponseBody() {
        }
        
        public insertEmployeeResponseBody(int insertEmployeeResult) {
            this.insertEmployeeResult = insertEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequestBody Body;
        
        public updateEmployeeRequest() {
        }
        
        public updateEmployeeRequest(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO;
        
        public updateEmployeeRequestBody() {
        }
        
        public updateEmployeeRequestBody(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            this.employeeBO = employeeBO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponseBody Body;
        
        public updateEmployeeResponse() {
        }
        
        public updateEmployeeResponse(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateEmployeeResult;
        
        public updateEmployeeResponseBody() {
        }
        
        public updateEmployeeResponseBody(int updateEmployeeResult) {
            this.updateEmployeeResult = updateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequestBody Body;
        
        public deleteEmployeeRequest() {
        }
        
        public deleteEmployeeRequest(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO;
        
        public deleteEmployeeRequestBody() {
        }
        
        public deleteEmployeeRequestBody(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            this.employeeBO = employeeBO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponseBody Body;
        
        public deleteEmployeeResponse() {
        }
        
        public deleteEmployeeResponse(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int deleteEmployeeResult;
        
        public deleteEmployeeResponseBody() {
        }
        
        public deleteEmployeeResponseBody(int deleteEmployeeResult) {
            this.deleteEmployeeResult = deleteEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAttendenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAttendence", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequestBody Body;
        
        public AddAttendenceRequest() {
        }
        
        public AddAttendenceRequest(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAttendenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.AttendenceBO attendenceBO;
        
        public AddAttendenceRequestBody() {
        }
        
        public AddAttendenceRequestBody(ManagementServiceUIWebService.ManagementServiceReference1.AttendenceBO attendenceBO) {
            this.attendenceBO = attendenceBO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAttendenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAttendenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponseBody Body;
        
        public AddAttendenceResponse() {
        }
        
        public AddAttendenceResponse(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAttendenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddAttendenceResult;
        
        public AddAttendenceResponseBody() {
        }
        
        public AddAttendenceResponseBody(int AddAttendenceResult) {
            this.AddAttendenceResult = AddAttendenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPerformenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPerformence", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequestBody Body;
        
        public AddPerformenceRequest() {
        }
        
        public AddPerformenceRequest(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPerformenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.PerfomanceBO perfomanceBO;
        
        public AddPerformenceRequestBody() {
        }
        
        public AddPerformenceRequestBody(ManagementServiceUIWebService.ManagementServiceReference1.PerfomanceBO perfomanceBO) {
            this.perfomanceBO = perfomanceBO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPerformenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPerformenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponseBody Body;
        
        public AddPerformenceResponse() {
        }
        
        public AddPerformenceResponse(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPerformenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddPerformenceResult;
        
        public AddPerformenceResponseBody() {
        }
        
        public AddPerformenceResponseBody(int AddPerformenceResult) {
            this.AddPerformenceResult = AddPerformenceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManagementServiceSoapChannel : ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementServiceSoapClient : System.ServiceModel.ClientBase<ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap>, ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap {
        
        public ManagementServiceSoapClient() {
        }
        
        public ManagementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.insertEmployee(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest request) {
            return base.Channel.insertEmployee(request);
        }
        
        public int insertEmployee(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse retVal = ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).insertEmployee(inValue);
            return retVal.Body.insertEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse> ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.insertEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest request) {
            return base.Channel.insertEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeResponse> insertEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.insertEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            return ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).insertEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.updateEmployee(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest request) {
            return base.Channel.updateEmployee(request);
        }
        
        public int updateEmployee(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse retVal = ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).updateEmployee(inValue);
            return retVal.Body.updateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse> ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.updateEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest request) {
            return base.Channel.updateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeResponse> updateEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.updateEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            return ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).updateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.deleteEmployee(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest request) {
            return base.Channel.deleteEmployee(request);
        }
        
        public int deleteEmployee(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse retVal = ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).deleteEmployee(inValue);
            return retVal.Body.deleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse> ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.deleteEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest request) {
            return base.Channel.deleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeResponse> deleteEmployeeAsync(ManagementServiceUIWebService.ManagementServiceReference1.EmployeeBO employeeBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.deleteEmployeeRequestBody();
            inValue.Body.employeeBO = employeeBO;
            return ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).deleteEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.AddAttendence(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest request) {
            return base.Channel.AddAttendence(request);
        }
        
        public int AddAttendence(ManagementServiceUIWebService.ManagementServiceReference1.AttendenceBO attendenceBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequestBody();
            inValue.Body.attendenceBO = attendenceBO;
            ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse retVal = ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).AddAttendence(inValue);
            return retVal.Body.AddAttendenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse> ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.AddAttendenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest request) {
            return base.Channel.AddAttendenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceResponse> AddAttendenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.AttendenceBO attendenceBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.AddAttendenceRequestBody();
            inValue.Body.attendenceBO = attendenceBO;
            return ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).AddAttendenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.AddPerformence(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest request) {
            return base.Channel.AddPerformence(request);
        }
        
        public int AddPerformence(ManagementServiceUIWebService.ManagementServiceReference1.PerfomanceBO perfomanceBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequestBody();
            inValue.Body.perfomanceBO = perfomanceBO;
            ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse retVal = ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).AddPerformence(inValue);
            return retVal.Body.AddPerformenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse> ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap.AddPerformenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest request) {
            return base.Channel.AddPerformenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceResponse> AddPerformenceAsync(ManagementServiceUIWebService.ManagementServiceReference1.PerfomanceBO perfomanceBO) {
            ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest inValue = new ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequest();
            inValue.Body = new ManagementServiceUIWebService.ManagementServiceReference1.AddPerformenceRequestBody();
            inValue.Body.perfomanceBO = perfomanceBO;
            return ((ManagementServiceUIWebService.ManagementServiceReference1.ManagementServiceSoap)(this)).AddPerformenceAsync(inValue);
        }
    }
}
